//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Priem = new HashSet<Priem>();
        }
    
        public int Kod_doctor { get; set; }
        public Nullable<int> Kod_plot { get; set; }
        public Nullable<int> Kod_raspisanie { get; set; }
        public Nullable<int> N_raspisanie { get; set; }
        public string Surname { get; set; }
        public string Name_ { get; set; }
        public string Middle_name { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public Nullable<int> Kod_pasport { get; set; }
        public string Adres { get; set; }
        public int Op_rabot { get; set; }
        public Nullable<int> Kod_specialnost { get; set; }
        public string Tel_ { get; set; }
        public string Mail { get; set; }
        public int Zarplata { get; set; }
        public Nullable<int> Kod_uslugi { get; set; }
    
        public virtual Pasport Pasport { get; set; }
        public virtual Klinika Klinika { get; set; }
        public virtual Specialnost Specialnost { get; set; }
        public virtual Uslugi Uslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Priem> Priem { get; set; }
        public virtual Raspisanie Raspisanie { get; set; }
    }
}
