//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int Kod_karta { get; set; }
        public Nullable<int> N_karta { get; set; }
        public Nullable<int> Kod_visits { get; set; }
        public System.DateTime Zapis { get; set; }
        public Nullable<int> Kod_diagnoz { get; set; }
    
        public virtual Diagnoz Diagnoz { get; set; }
        public virtual Visits Visits { get; set; }
    }
}
