//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visits()
        {
            this.Karta = new HashSet<Karta>();
        }
    
        public int Kod_visits { get; set; }
        public Nullable<int> Kod_obsledovaniye { get; set; }
        public System.DateTime Zapis_visits { get; set; }
        public System.DateTime Data_priema { get; set; }
        public Nullable<int> N_karta { get; set; }
        public int Kod_zapisi { get; set; }
        public Nullable<int> Kod_zhaloba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta> Karta { get; set; }
        public virtual Obsledovaniye Obsledovaniye { get; set; }
        public virtual Priem Priem { get; set; }
        public virtual Zhaloba Zhaloba { get; set; }
    }
}
